### ISSUE TITLE
Please describe requirement about "diff" algorithm

### ISSUE THREAD

**Issue by markzyu** [TikhonJelvis/Cow#1]
I have been reading the code but cannot figure out the algorithm used here (in src/Cow/Diff.hs) and I cannot understand the constraints on its outputs either.

For example: If we reorder the children of a node, how should we output it? What are the definitions of all possible types of changes in an AST?

Thanks!

**Comment by TikhonJelvis** [comment]
Sorry, the old code is a mess because _I_ didn't know what I wanted! It was essentially a long exercise in working out my intuition. (This is part of why this whole repo is barely a proof-of-concept.) I've since gotten a better idea of what I want to accomplish but haven't implemented or written it up.

Here's a quick sketch.

The idea behind the whole system is a _pipeline_ with two core pieces:
1. A diff algorithm that compares trees rather than strings and produces a tree annotated with added or removed nodes (ie a tree-shaped edit script).
2. An algorithm that matches up sub-trees from the input and output to detect moves. Currently this works through bipartite graph matching between all the sub-trees from both trees. (Bipartite matching is what the [Hungarian method](https://en.wikipedia.org/wiki/Hungarian_algorithm) library I call out to calculates.)

In the current code, 1. is handled by Diff.hs and 2. by Substructure.hs.

Diff.hs is a complete mess. I didn't have a good specification for what I wanted and implemented it in a catastrophically inefficient way. Happily, I've since figured out a good way to specify the algorithm and a (hopefully) efficient implementation as a variant of the standard string edit distance algorithm ([Wagner-Fischer](https://en.wikipedia.org/wiki/Wagner%E2%80%93Fischer_algorithm).

The goal behind the diff step is to get the usual additions/deletions you expect from a normal diff but informed by the syntactic structure of the code. The idea is to group "local" changes together: if you changed 75% of the tokens in a line, or 75% of the lines in a block, we want to mark _the whole block_ as changed. Apart from being intuitive on its own, I think this will also help detecting moved blocks holistically, instead of just tracking things line-by-line.

One of the changes is that I now care about _parse trees_ rather than ASTs. This means that every single token is preserved in order in the leaves, with the tree just grouping related tokens together. This idea is common in linguistics and fits well here; here's a visualization of what I mean:

![A parse tree for a sentence.](https://upload.wikimedia.org/wikipedia/commons/5/54/Parse_tree_1.jpg)

All the original lexical information is preserved at the leaves.

With this in mind, the operations we care about on the tree are adding and removing _whole subtrees_ (which might only contain a single leaf but might also cover more). Since these inherently overlap, we need some heuristic weighting function to minimize that tells us when we should look at small bits separately and when enough things changed to just mark the whole subtree instead.

Normal edit distance often allows modifying a character rather than just adding or removing it. I don't care about modifying partly because I'm not sure how to generalize it to subtrees but mostly because it gets calculated in a more useful way as part of move detection in step 2.

I have a rough first draft of the [new algorithm](https://github.com/TikhonJelvis/Cow/blob/parse-trees/src/Cow/Diff.hs) on another branch, although it only calculate the distance as a number at the moment.

I also have some ideas on how to improve step 2 because my current approach based on bipartite graph matching has some limitations, but I want to finish up the initial diff pass before working on it.

Does all this make sense? 

I've been meaning to sit down, finish and test the diff code and write all this up more coherently, but have been procrastinating on it a bit. This response is more a stream of consciousness about what I've been thinking than I'd like; hopefully I'll have a more measured and understandable description soon—perhaps borrowing Simon Peyton Jones's "paper-first" approach because I really need the clarity and organization that a solid write up provides.

**Comment by markzyu** [comment]
Thanks for such a detailed response! 👍 

After reading it seems to me that Diff.hs is just trying to detect additions and deletions, and at the meantime it might convert a block with dense changes to a whole changed block. Did I understand your target correctly?

If so I think it's possible that there is a simpler algorithm (maybe not so well-known) to accomplish this task. I wonder why we are using a "edit distance" algorithm _designed for string_. (Is it practical to simply rely on  more basic evaluations, such as (total length of text in changed subtree) / (total length of text in subtree))?

**Comment by TikhonJelvis** [comment]
What you described (evaluating a subtree based on changed text/total text) would be the heuristic that the algorithm uses to weigh a subtree addition or deletion. Even with this we still need to choose a _minimal sequence_ of additions and deletions. 

Think about it this way: at each point, we always have the tradeoff of, say, deleting _this_ subtree or deleting multiple other ones, and we need to choose based on what would minimize the set of changes as a whole. The Wagner-Fischer algorithm just provides the skeleton to do this efficiently using dynamic programming.

Now, it's possible that I could use bog-standard string edit distance, find the deletions/additions and then consolidate them using our parse tree in a separate pass. However, I'm not convinced this would be easier to do, and I suspect the algorithm would end up isomorphic to what I have now.

**Comment by markzyu** [comment]
I see... It makes sense now. And I should look into the algorithms you
mentioned before trying to optimize it. Thanks for the information!

**Comment by TikhonJelvis** [comment]
Good to hear. If you're interested, I wrote a blog post that describes the Wagner-Fischer algorithm and the specific technique I used to implement in in Haskell: [Lazy Dynamic Programming](http://jelv.is/blog/Lazy-Dynamic-Programming). The new code I'm working on now is directly based on what I wrote there.

**Comment by TikhonJelvis** [comment]
Also, I'm currently moving this project over to [GitLab](https://gitlab.com/tikhon/Cow). (My long-term plan is to move all my work over there.) I'll still pay attention to this thread, and I'll probably still use this repo as a mirror, but my new changes will probably appear on GitLab first.

**Comment by markzyu** [comment]
My confusion has been solved. Thanks :)
